[package]
name = "d2-kernel"
version = "0.0.1"
authors = ["Blake Loring <blake@parsed.uk>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0.4"

[profile.debug]
panic = "abort"

[profile.release]
panic = "abort"
